import { language } from '../i18n/index.ts'

const en = {
  intro: 'Make it yours.',
  description: 'Choose a look, then give it your colours.',
  figure: 'Figure',
  sex: 'Character',
  male: 'Male',
  female: 'Female',
  shoulder: 'Shoulders',
  bust: 'Chest',
  waist: 'Waist',
  hip: 'Hips',
  head: 'Head size',
  figureEven: 'Even',
  figureBroad: 'Broad',
  figureCurved: 'Curved',
  figureYoung: 'Petite',
  looks: 'Looks',
  hair: 'Hair',
  colours: 'Colours',
  expression: 'Expression',
  none: 'No equipment',
  gear: 'Explorer gear',
  equipment: 'Equipment',
  pack: 'Backpack',
  arms: 'Arm gear',
  visor: 'Visor',
  hairstyle: 'Hairstyle',
  mint: 'Mint',
  ember: 'Ember',
  frost: 'Frost',
  rose: 'Rose',
  copper: 'Copper',
  ink: 'Ink',
  violet: 'Violet',
  lime: 'Lime',
  tails: 'Ponytail',
  bob: 'Short bob',
  long: 'Long hair',
  neutral: 'Calm',
  happy: 'Happy',
  relaxed: 'Relaxed',
  hairColour: 'Hair',
  eyeColour: 'Eyes',
  outfitColour: 'Outfit',
  skinColour: 'Skin',
  backdrop: 'Background',
  apply: 'Save',
  cancel: 'Cancel',
  random: 'Surprise me',
  loading: 'Preparing your character…',
  loadingNote: 'First visit downloads an 11 MB model. It is cached for later visits.',
  failed:
    'The 3D character could not load. Check your connection or try a WebGL-compatible browser.',
  retry: 'Try again',
  ready: 'Save keeps your changes.',
  saved: 'Saved on this device.',
  syncing: 'Saved on this device. Syncing profile…',
  synced: 'Saved to your profile.',
  syncFailed: 'Saved on this device. Profile sync failed; try applying again when connected.',
  storageFailed: 'This browser could not save your character. Free some storage and try again.',
  discard: 'Discard your unsaved character changes?',
  keep: 'Keep editing',
  leave: 'Discard changes',
  portrait: 'Face',
  full: 'Full body',
  framing: 'Preview framing',
  direction: 'Viewing direction',
  front: 'Front',
  side: 'Side',
  back: 'Rear',
  portraitNote: 'Your profile uses a face portrait of this full-body character.',
  left: 'Rotate left',
  right: 'Rotate right',
  rotate: 'Drag to rotate. Use arrow keys when the preview is focused; Home resets the view.',
  credit: 'Seed-san · VirtualCast, Inc. · VRM Public License 1.0',
  preview: '3D character preview',
  close: 'Back to profile',
}
type Copy = Record<keyof typeof en, string>
const ko: Copy = {
  intro: '나만의 캐릭터.',
  description: '마음에 드는 스타일에 나만의 색을 더하세요.',
  figure: '체형',
  sex: '캐릭터',
  male: '남성',
  female: '여성',
  shoulder: '어깨',
  bust: '가슴',
  waist: '허리',
  hip: '엉덩이',
  head: '머리 크기',
  figureEven: '기본',
  figureBroad: '역삼각',
  figureCurved: '곡선',
  figureYoung: '아담',
  looks: '스타일',
  hair: '헤어',
  colours: '색상',
  expression: '표정',
  none: '장비 없음',
  gear: '탐험 장비',
  equipment: '장비',
  pack: '배낭',
  arms: '암 기어',
  visor: '바이저',
  hairstyle: '헤어스타일',
  mint: '민트',
  ember: '앰버',
  frost: '프로스트',
  rose: '로즈',
  copper: '코퍼',
  ink: '잉크',
  violet: '바이올렛',
  lime: '라임',
  tails: '포니테일',
  bob: '단발',
  long: '긴 머리',
  neutral: '차분하게',
  happy: '밝게',
  relaxed: '편안하게',
  hairColour: '머리',
  eyeColour: '눈',
  outfitColour: '의상',
  skinColour: '피부',
  backdrop: '배경',
  apply: '저장',
  cancel: '취소',
  random: '랜덤 스타일',
  loading: '캐릭터를 준비하고 있어요…',
  loadingNote: '처음에는 약 11 MB 모델을 받아요. 다음 방문을 위해 기기에 보관해요.',
  failed:
    '3D 캐릭터를 불러오지 못했어요. 연결을 확인하거나 WebGL을 지원하는 브라우저에서 다시 시도해 주세요.',
  retry: '다시 시도',
  ready: '저장을 누르면 반영돼요.',
  saved: '이 기기에 저장했어요.',
  syncing: '이 기기에 저장했어요. 프로필 동기화 중…',
  synced: '프로필에 저장했어요.',
  syncFailed:
    '이 기기에 저장했어요. 연결이 복구되면 적용 버튼으로 프로필 동기화를 다시 시도해 주세요.',
  storageFailed:
    '캐릭터를 저장할 공간이 부족하거나 저장이 차단되어 있어요. 확인 후 다시 시도해 주세요.',
  discard: '저장하지 않은 변경을 취소할까요?',
  keep: '계속 편집',
  leave: '변경 취소',
  portrait: '얼굴',
  full: '전신',
  framing: '미리보기 범위',
  direction: '보는 방향',
  front: '정면',
  side: '측면',
  back: '후면',
  portraitNote: '프로필에는 이 전신 캐릭터의 얼굴 이미지가 표시돼요.',
  left: '왼쪽 회전',
  right: '오른쪽 회전',
  rotate:
    '드래그로 회전해요. 미리보기에 초점을 맞춘 뒤 방향키로 회전하고 Home 키로 정면을 볼 수 있어요.',
  credit: 'Seed-san · VirtualCast, Inc. · VRM Public License 1.0',
  preview: '3D 캐릭터 미리보기',
  close: '프로필로 돌아가기',
}
const ja: Copy = {
  intro: '自分らしいキャラクター。',
  description: 'スタイルを選んで、自分の色を加えよう。',
  figure: '体型',
  sex: 'キャラクター',
  male: '男性',
  female: '女性',
  shoulder: '肩',
  bust: '胸',
  waist: '腰',
  hip: 'ヒップ',
  head: '頭の大きさ',
  figureEven: '標準',
  figureBroad: '逆三角',
  figureCurved: '曲線',
  figureYoung: '小柄',
  looks: 'スタイル',
  hair: '髪',
  colours: 'カラー',
  expression: '表情',
  none: '装備なし',
  gear: '探検装備',
  equipment: '装備',
  pack: 'リュック',
  arms: 'アームギア',
  visor: 'バイザー',
  hairstyle: '髪型',
  mint: 'ミント',
  ember: 'アンバー',
  frost: 'フロスト',
  rose: 'ローズ',
  copper: 'カッパー',
  ink: 'インク',
  violet: 'バイオレット',
  lime: 'ライム',
  tails: 'ポニーテール',
  bob: 'ボブ',
  long: 'ロング',
  neutral: '穏やか',
  happy: '笑顔',
  relaxed: 'リラックス',
  hairColour: '髪',
  eyeColour: '瞳',
  outfitColour: '服',
  skinColour: '肌',
  backdrop: '背景',
  apply: '保存',
  cancel: 'キャンセル',
  random: 'ランダム',
  loading: 'キャラクターを準備中…',
  loadingNote: '初回は約11 MBをダウンロードし、次回のために保存します。',
  failed: '3Dキャラクターを読み込めません。接続を確認するか、WebGL対応ブラウザーでお試しください。',
  retry: '再試行',
  ready: '適用すると変更が保存されます。',
  saved: 'この端末に保存しました。',
  syncing: '端末に保存済み。プロフィールを同期中…',
  synced: 'プロフィールに保存しました。',
  syncFailed: '端末に保存済み。接続後、適用ボタンで同期を再試行してください。',
  storageFailed: '保存できません。空き容量と保存設定を確認してください。',
  discard: '未保存の変更を破棄しますか？',
  keep: '編集を続ける',
  leave: '変更を破棄',
  portrait: '顔',
  full: '全身',
  framing: '表示範囲',
  direction: '見る方向',
  front: '正面',
  side: '側面',
  back: '背面',
  portraitNote: 'プロフィールには、この全身キャラクターの顔が表示されます。',
  left: '左に回転',
  right: '右に回転',
  rotate: 'ドラッグで回転。プレビューにフォーカスすると矢印キーで回転、Homeキーで正面に戻ります。',
  credit: 'Seed-san · VirtualCast, Inc. · VRM Public License 1.0',
  preview: '3Dキャラクタープレビュー',
  close: 'プロフィールに戻る',
}
const zh: Copy = {
  intro: '打造你的角色。',
  description: '选择风格，再加上自己的色彩。',
  figure: '体型',
  sex: '角色',
  male: '男性',
  female: '女性',
  shoulder: '肩部',
  bust: '胸部',
  waist: '腰部',
  hip: '臀部',
  head: '头部大小',
  figureEven: '基本',
  figureBroad: '倒三角',
  figureCurved: '曲线',
  figureYoung: '娇小',
  looks: '风格',
  hair: '头发',
  colours: '颜色',
  expression: '表情',
  none: '无装备',
  gear: '探索装备',
  equipment: '装备',
  pack: '背包',
  arms: '臂甲',
  visor: '护镜',
  hairstyle: '发型',
  mint: '薄荷',
  ember: '琥珀',
  frost: '冰霜',
  rose: '玫瑰',
  copper: '铜橙',
  ink: '墨黑',
  violet: '紫罗兰',
  lime: '青柠',
  tails: '马尾',
  bob: '短发',
  long: '长发',
  neutral: '平静',
  happy: '开心',
  relaxed: '放松',
  hairColour: '头发',
  eyeColour: '眼睛',
  outfitColour: '服装',
  skinColour: '肤色',
  backdrop: '背景',
  apply: '保存',
  cancel: '取消',
  random: '随机风格',
  loading: '正在准备角色…',
  loadingNote: '首次下载约11 MB模型，并缓存以供下次使用。',
  failed: '无法加载3D角色。请检查网络或使用支持WebGL的浏览器。',
  retry: '重试',
  ready: '应用后保存更改。',
  saved: '已保存在此设备。',
  syncing: '已保存在此设备，正在同步资料…',
  synced: '已保存至个人资料。',
  syncFailed: '已保存在此设备。联网后请点击应用重试同步。',
  storageFailed: '无法保存。请检查存储空间和浏览器设置。',
  discard: '放弃未保存的更改？',
  keep: '继续编辑',
  leave: '放弃更改',
  portrait: '面部',
  full: '全身',
  framing: '预览范围',
  direction: '查看方向',
  front: '正面',
  side: '侧面',
  back: '背面',
  portraitNote: '个人资料将显示这个全身角色的面部头像。',
  left: '向左旋转',
  right: '向右旋转',
  rotate: '拖动旋转。预览获得焦点后，可用方向键旋转，Home键恢复正面。',
  credit: 'Seed-san · VirtualCast, Inc. · VRM Public License 1.0',
  preview: '3D角色预览',
  close: '返回个人资料',
}
export function animeCopy(): Copy {
  return { en, ko, ja, 'zh-Hans': zh }[language()]
}
