import { language } from '../i18n/index.ts'

const en = {
  angry: 'Determined', sad: 'Sad', surprised: 'Surprised', library: 'Saved',
  undo: 'Undo', redo: 'Redo', reset: 'Reset look', pause: 'Pause motion',
  name: 'Look name', saveLook: 'Save this look', load: 'Load', remove: 'Delete', confirm: 'Confirm delete',
  empty: 'Keep your favourite looks here. Nothing changes your profile until you apply.',
  local: 'Up to 12 looks on this browser. Export a character file to keep a backup or move to another device.',
  savedLook: 'Look saved in this browser.', full: 'All 12 slots are full. Export a backup before deleting a look.',
  nameRequired: 'Give this look a name (up to 32 characters).', loaded: 'Look loaded as a draft. Apply to use it.',
  removed: 'Saved look deleted. Your current profile is unchanged.',
  openFiles: 'Files & exports',
  files: 'Save files & restore', exportLook: 'Character file (.json)', importLook: 'Restore character file',
  fileHelp: 'Restore a Chroma character JSON file (up to 16 KB). It changes only the draft, never your saved profile.',
  invalid: 'This file is not a supported Chroma character file. Your draft is unchanged.',
  downloads: 'Images & 3D model', face: 'Face PNG', body: 'Full-body PNG', sheet: '4-view sheet PNG',
  sheetExpand: 'Show more options', sheetCollapse: 'Show less, and more of the character', transparent: 'Transparent image background', vrm: 'Avatar (.vrm)', glb: '3D model (.glb)',
  modelNote: 'VRM / GLB preserve colours, hair, equipment, rig and model permissions. Exported models use the rest pose; preview gestures and selected expression are not baked in. GLB appearance depends on MToon support.',
  working: 'Preparing download…', downloaded: 'File prepared. Check your browser downloads.',
  failed: 'Could not prepare the file. Your character is unchanged; please try again.',
  gaze: 'On desktop, the character follows your pointer inside the preview. Reduced motion disables automatic movement.',
}
type Copy = Record<keyof typeof en, string>
const ko: Copy = {
  angry: '당당하게', sad: '슬프게', surprised: '놀라게', library: '보관함',
  undo: '되돌리기', redo: '다시 실행', reset: '기본 모습', pause: '동작 멈춤',
  name: '캐릭터 이름', saveLook: '이 모습 보관', load: '불러오기', remove: '삭제', confirm: '삭제 확인',
  empty: '마음에 드는 모습을 보관하세요. 적용하기 전에는 프로필이 바뀌지 않아요.',
  local: '이 브라우저에 최대 12개를 보관해요. 다른 기기로 옮기거나 백업하려면 캐릭터 파일을 저장하세요.',
  savedLook: '이 브라우저의 보관함에 저장했어요.', full: '보관함 12개가 모두 찼어요. 삭제 전 파일로 백업할 수 있어요.',
  nameRequired: '캐릭터 이름을 32자 이내로 입력해 주세요.', loaded: '편집할 모습으로 불러왔어요. 적용하면 프로필이 바뀌어요.',
  removed: '보관한 모습을 삭제했어요. 현재 프로필은 그대로예요.',
  openFiles: '파일 · 내보내기',
  files: '파일 저장 · 복원', exportLook: '캐릭터 파일 (.json)', importLook: '캐릭터 파일 복원',
  fileHelp: 'Chroma 캐릭터 JSON 파일(최대 16 KB)을 불러와요. 저장된 프로필은 바뀌지 않고 편집 중인 모습만 변경돼요.',
  invalid: '지원하는 Chroma 캐릭터 파일이 아니에요. 편집 중인 모습은 그대로예요.',
  downloads: '이미지 · 3D 모델', face: '얼굴 PNG', body: '전신 PNG', sheet: '4방향 시트 PNG',
  sheetExpand: '선택 영역 넓게 보기', sheetCollapse: '캐릭터 크게 보기', transparent: '이미지 배경 투명하게', vrm: '아바타 (.vrm)', glb: '3D 모델 (.glb)',
  modelNote: 'VRM / GLB에는 색상·헤어·장비·뼈대와 모델 이용 조건이 유지돼요. 기본 포즈로 내보내며 미리보기 제스처와 선택한 표정은 구워 넣지 않아요. GLB의 표현은 MToon 지원 여부에 따라 달라져요.',
  working: '다운로드를 준비하고 있어요…', downloaded: '파일을 준비했어요. 브라우저의 다운로드를 확인하세요.',
  failed: '파일을 만들지 못했어요. 캐릭터는 그대로예요. 다시 시도해 주세요.',
  gaze: 'PC에서는 미리보기 안의 포인터를 따라 시선이 움직여요. 동작 줄이기를 사용하면 자동 움직임을 멈춰요.',
}
const ja: Copy = {
  angry: 'きりっと', sad: '悲しい', surprised: 'びっくり', library: '保存',
  undo: '元に戻す', redo: 'やり直す', reset: '初期の姿', pause: '動きを停止',
  name: '名前', saveLook: 'この姿を保存', load: '読込', remove: '削除', confirm: '削除を確認',
  empty: 'お気に入りの姿を保存できます。適用するまでプロフィールは変わりません。',
  local: 'このブラウザーに最大12件保存。バックアップや他の端末への移行にはキャラクターファイルを保存してください。',
  savedLook: 'このブラウザーに保存しました。', full: '12件すべて使用中です。削除前にファイルでバックアップできます。',
  nameRequired: '32文字以内の名前を入力してください。', loaded: '編集中の姿に読み込みました。適用するとプロフィールが変わります。',
  removed: '保存した姿を削除しました。プロフィールは変わりません。',
  openFiles: 'ファイル・書き出し',
  files: 'ファイル保存・復元', exportLook: 'キャラクターファイル (.json)', importLook: 'ファイルを復元',
  fileHelp: 'ChromaのJSONファイル（最大16 KB）を復元します。編集中の姿のみ変更します。',
  invalid: '対応するChromaファイルではありません。編集中の姿は変わりません。',
  downloads: '画像・3Dモデル', face: '顔 PNG', body: '全身 PNG', sheet: '4方向シート PNG',
  sheetExpand: '選択エリアを広げる', sheetCollapse: 'キャラクターを大きく', transparent: '画像の背景を透明に', vrm: 'アバター (.vrm)', glb: '3Dモデル (.glb)',
  modelNote: '色・髪・装備・骨格・利用条件を維持。モデルは基本姿勢で、プレビューの動作・選択した表情は含みません。GLBの表示はMToon対応によって異なります。',
  working: 'ファイルを準備中…', downloaded: 'ファイルを準備しました。ダウンロードを確認してください。',
  failed: 'ファイルを作成できませんでした。キャラクターは変わりません。再試行してください。',
  gaze: 'PCではプレビュー内のポインターを目で追います。動きを減らす設定では自動動作を停止します。',
}
const zh: Copy = {
  angry: '坚定', sad: '伤心', surprised: '惊讶', library: '收藏',
  undo: '撤销', redo: '重做', reset: '初始造型', pause: '暂停动作',
  name: '造型名称', saveLook: '收藏此造型', load: '载入', remove: '删除', confirm: '确认删除',
  empty: '在这里收藏喜欢的造型。应用前不会改变个人资料。',
  local: '此浏览器最多保存12个造型。导出角色文件以备份或转移至其他设备。',
  savedLook: '已在此浏览器中收藏。', full: '12个位置已满。删除前可导出文件备份。',
  nameRequired: '请输入不超过32个字符的名称。', loaded: '已载入编辑草稿。应用后才会改变个人资料。',
  removed: '已删除收藏。当前个人资料未改变。',
  openFiles: '文件与导出',
  files: '文件保存与恢复', exportLook: '角色文件 (.json)', importLook: '恢复角色文件',
  fileHelp: '恢复Chroma角色JSON文件（最多16 KB）。只改变草稿，不会覆盖已保存的个人资料。',
  invalid: '这不是支持的Chroma角色文件。草稿未改变。',
  downloads: '图片与3D模型', face: '面部 PNG', body: '全身 PNG', sheet: '四视图 PNG',
  sheetExpand: '展开选项区域', sheetCollapse: '放大角色', transparent: '透明图片背景', vrm: '虚拟形象 (.vrm)', glb: '3D模型 (.glb)',
  modelNote: '保留颜色、发型、装备、骨骼与使用条件。模型使用基础姿势，不包含预览动作与所选表情。GLB外观取决于MToon支持。',
  working: '正在准备下载…', downloaded: '文件已准备。请检查浏览器下载。',
  failed: '无法生成文件。角色未改变，请重试。',
  gaze: '在电脑上，视线会跟随预览中的指针。减少动态效果设置会停止自动动作。',
}
export function studioToolsCopy(): Copy { return { en, ko, ja, 'zh-Hans': zh }[language()] }
