import { expect, test, type Page } from '@playwright/test'
const touchTest = test.extend({hasTouch:true})
const retinaTest = test.extend({deviceScaleFactor:3})

async function boot(page: Page) {
  await page.route(/googleapis\.com|firebaseio\.com|firebaseapp\.com|seed-san\.vrm/, route=>route.abort())
  await page.addInitScript(()=>{localStorage.setItem('chroma-match:granted','1');localStorage.setItem('chroma-match:lang','ko')})
  await page.goto('/?seed=7'); await expect(page.locator('#splash')).toBeHidden()
}

test('camera keeps 52px stage targets, pans without selecting, keyboard reveals stages and shared navigation preserves camera', async ({page},info)=>{
  await page.setViewportSize({width:390,height:844}); await boot(page)
  await page.locator('[data-region="forest"]').click()
  await expect(page.locator('.world-mission')).toHaveCount(30)
  const read=()=>page.locator('.world-plane').evaluate(e=>getComputedStyle(e).transform)
  const size=()=>page.locator('[data-mission-step="1"]').evaluate(e=>e.getBoundingClientRect().width)
  const original=await read()
  await page.locator('[data-camera="in"]').click()
  expect(await read()).not.toBe(original); expect(await size()).toBeCloseTo(52,1)
  await page.mouse.move(210,440); await page.mouse.down(); await page.mouse.move(230,540,{steps:8}); await page.mouse.up()
  await expect(page.locator('[data-mission-step="1"]')).toHaveAttribute('aria-pressed','true')
  expect(await page.evaluate(()=>document.documentElement.scrollTop)).toBe(0)
  await page.locator('[data-mission-step="30"]').focus()
  await expect(page.locator('[data-mission-step="30"]')).toBeInViewport()
  await page.locator('#world-art').focus(); await page.keyboard.press('Home')
  await expect(page.locator('[data-mission-step="1"]')).toBeInViewport()
  await expect.poll(()=>page.locator('.world-plane').evaluate(e=>{
    const actual=new DOMMatrix(getComputedStyle(e).transform),target=new DOMMatrix((e as HTMLElement).style.transform)
    return Math.abs(actual.m41-target.m41)+Math.abs(actual.m42-target.m42)
  })).toBeLessThan(.1)
  await page.screenshot({path:info.outputPath('forest-region-mobile.png')})
  const camera=await read()
  await page.locator('#map-shop').click()
  await expect(page.locator('.hub-header')).toBeVisible(); await expect(page.locator('#map-shop')).toHaveAttribute('aria-current','page')
  await page.locator('#map-shop').click() // Re-selecting the tab must not replace its return destination.
  await page.locator('#shop-back').click()
  await expect(page.locator('#screen-map')).toBeVisible();await expect(page.locator('#map-shop')).toBeFocused()
  expect(await read()).toBe(camera)
  await page.locator('#map-shop').click()
  await page.locator('#world-list-label').click()
  await expect(page.locator('#screen-map')).toBeVisible(); expect(await read()).toBe(camera)
  await page.locator('#world-art').focus(); await page.keyboard.press('Escape')
  await expect(page.locator('#screen-map')).toHaveAttribute('data-map-view','world')
  await page.locator('#map-character').click()
  await expect(page.locator('#screen-home')).toBeVisible(); await expect(page.locator('#map-character')).toHaveAttribute('aria-current','page')
  await page.locator('#start-game').click(); await page.locator('#loadout-start').click()
  await expect(page.locator('.hub-header')).toBeHidden(); await expect(page.locator('.hub-nav')).toBeHidden()
  await expect(page.locator('#hud-player-level')).toHaveText('Lv.1')
})

test('world overview fixed controls remain visible and unoccluded across phone, fold and desktop sizes',async({page},info)=>{
  await boot(page)
  for(const [width,height]of[[320,568],[390,690],[390,844],[480,320],[844,390],[720,720],[1280,800]]){
    await page.setViewportSize({width:width!,height:height!})
    await expect.poll(()=>page.evaluate(()=>{
      const nodes=[...document.querySelectorAll<HTMLElement>('.world-pin,.world-quick,#world-play,#map-wallet,#map-profile,.world-utilities > button,.world-nav > button,.world-list > summary')]
      const errors:string[]=[]
      for(const e of nodes){const r=e.getBoundingClientRect();const name=e.id||e.dataset.region||e.className
        if(r.width<44||r.height<44)errors.push(`${name}:size`)
        if(r.x<0||r.y<0||r.right>innerWidth+.5||r.bottom>innerHeight+.5)errors.push(`${name}:clip`)
        if(!e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)))errors.push(`${name}:occluded`)
      }
      if(document.documentElement.scrollWidth>innerWidth)errors.push('overflow')
      return errors
    }),{message:`${width}x${height} map target geometry`}).toEqual([])
    await page.screenshot({path:info.outputPath(`world-${width}x${height}.png`)})
  }
})

touchTest('two-finger zoom keeps targets fixed, and touch cancellation does not swallow subsequent keyboard selection',async({page})=>{
  await page.setViewportSize({width:390,height:844});await boot(page)
  await page.locator('[data-region="forest"]').click()
  await expect(page.locator('[data-mission-step="1"]')).toBeInViewport()
  const matrix=()=>page.locator('.world-plane').evaluate(e=>getComputedStyle(e).transform)
  const before=await matrix(),session=await page.context().newCDPSession(page)
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:170,y:400,id:1},{x:230,y:400,id:2}]})
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:130,y:400,id:1},{x:270,y:400,id:2}]})
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
  expect(await matrix()).not.toBe(before)
  expect(await page.locator('[data-mission-step="1"]').evaluate(e=>e.getBoundingClientRect().width)).toBeCloseTo(52,1)
  await expect(page.locator('[data-mission-step="1"]')).toHaveAttribute('aria-pressed','true')
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:220,y:420,id:3}]})
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:220,y:490,id:3}]})
  await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]})
  await page.locator('[data-mission-step="2"]').focus();await page.keyboard.press('Enter')
  await expect(page.locator('[data-mission-step="2"]')).toHaveAttribute('aria-pressed','true')
  expect(await page.evaluate(()=>document.documentElement.scrollTop)).toBe(0)
  await session.detach()
})

touchTest('regional touch drag tracks reversal, preserves node taps and leaves browser scrolling at zero',async({page})=>{
  await page.setViewportSize({width:390,height:844}); await boot(page)
  await page.locator('[data-region="forest"]').tap()
  await expect.poll(()=>page.locator('.world-plane').evaluate(e=>getComputedStyle(e).transitionDuration)).toBe('0.24s')
  // Start during the focus transition: a touch must pick up its visible position.
  const before=await page.locator('.world-plane').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m42)
  const session=await page.context().newCDPSession(page)
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:210,y:410,id:1}]})
  const start=await page.locator('.world-plane').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m42)
  expect(Math.abs(start-before)).toBeLessThan(220)
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:210,y:470,id:1}]})
  await expect(page.locator('#world-art')).toHaveAttribute('data-dragging','true')
  await expect(page.locator('.map-life-surface')).toBeHidden()
  expect(await page.locator('#world-image').evaluate(e=>getComputedStyle(e).opacity)).toBe('1')
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:210,y:412,id:1}]})
  await expect.poll(()=>page.locator('.world-plane').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m42)).toBeCloseTo(start+2,0)
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
  await expect(page.locator('#world-art')).not.toHaveAttribute('data-dragging','true')
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','running')
  await page.locator('[data-camera="focus"]').tap()
  await page.locator('[data-mission-step="1"]').tap()
  await expect(page.locator('[data-mission-step="1"]')).toHaveAttribute('aria-pressed','true')
  expect(await page.evaluate(()=>document.documentElement.scrollTop)).toBe(0)
  await session.detach()
})

test('map surface life is decorative, stops under sheets and hidden tabs, and respects reduced motion',async({page},info)=>{
  const errors:string[]=[]; page.on('pageerror',error=>errors.push(error.message))
  await page.setViewportSize({width:390,height:844}); await boot(page)
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','running')
  await expect(page.locator('.map-life-surface')).toBeVisible()
  expect(await page.locator('.map-life-surface').evaluate(e=>getComputedStyle(e).pointerEvents)).toBe('none')
  await page.locator('[data-region="forest"]').click()
  await expect(page.locator('#world-image')).toHaveAttribute('src',/forest/)
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','running')
  await expect.poll(()=>page.locator('.map-life-flight img').evaluateAll(nodes=>nodes.every(e=>(e as HTMLImageElement).complete && (e as HTMLImageElement).naturalWidth>0))).toBe(true)
  await page.screenshot({path:info.outputPath('living-forest.png')})
  await page.locator('#map-profile').click()
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','paused')
  await page.locator('#profile-close').click()
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','running')
  await page.locator('#map-shop').click()
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','paused')
  await page.locator('#world-list-label').click()
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','running')
  await page.emulateMedia({reducedMotion:'reduce'})
  await expect(page.locator('.map-life-surface')).toBeHidden()
  await expect(page.locator('.map-life-fauna')).toBeHidden()
  await expect(page.locator('#world-image')).toBeVisible()
  await page.emulateMedia({reducedMotion:'no-preference'})
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','running')
  await page.locator('.map-life-surface').evaluate(e=>(e as HTMLCanvasElement).getContext('webgl')!.getExtension('WEBGL_lose_context')!.loseContext())
  await expect(page.locator('.map-life-surface')).toBeHidden()
  await expect(page.locator('#world-image')).toBeVisible()
  await page.locator('[data-camera="world"]').click()
  await expect(page.locator('[data-region="forest"]')).toBeVisible()
  expect(errors).toEqual([])
})

test('WebGL unavailable retains the original artwork and functional map controls',async({page})=>{
  const errors:string[]=[]; page.on('pageerror',error=>errors.push(error.message))
  await page.addInitScript(()=>{
    const original=HTMLCanvasElement.prototype.getContext
    HTMLCanvasElement.prototype.getContext=function(kind:string,...args:unknown[]){
      if(kind==='webgl')return null
      return original.apply(this,[kind,...args] as Parameters<typeof original>)
    } as typeof original
  })
  await boot(page)
  await expect(page.locator('.map-life-surface')).toBeHidden()
  await expect(page.locator('#world-image')).toBeVisible()
  await page.locator('[data-region="forest"]').click()
  await page.locator('[data-camera="in"]').click()
  await expect(page.locator('[data-mission-step="1"]')).toHaveAttribute('aria-pressed','true')
  expect(errors).toEqual([])
})

test('high resolution sources retain logical coordinates and viewport-density animation',async({page},info)=>{
  await page.setViewportSize({width:390,height:844}); await boot(page)
  const dimensions=()=>page.locator('#world-image').evaluate(e=>[(e as HTMLImageElement).naturalWidth,(e as HTMLImageElement).naturalHeight])
  await expect.poll(dimensions).toEqual([2048,3072])
  await page.locator('[data-region="forest"]').click()
  await expect(page.locator('#world-image')).toHaveAttribute('src',/forest-v2/)
  await expect.poll(dimensions).toEqual([2048,3072])
  await page.locator('[data-camera="in"]').click()
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','running')
  const density=await page.locator('.map-life-surface').evaluate(e=>{
    const canvas=e as HTMLCanvasElement, view=e.parentElement!.getBoundingClientRect()
    return {width:canvas.width,height:canvas.height,viewWidth:view.width,viewHeight:view.height,dpr:devicePixelRatio,parent:e.parentElement!.id}
  })
  expect(density.parent).toBe('world-art')
  expect(density.width).toBeCloseTo(density.viewWidth*Math.min(density.dpr,3),0)
  expect(density.height).toBeCloseTo(density.viewHeight*Math.min(density.dpr,3),0)
  expect(density.width*density.height).toBeLessThanOrEqual(3_205_000)
  await page.waitForTimeout(400)
  await page.screenshot({path:info.outputPath('highres-forest-motion.png')})
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.screenshot({path:info.outputPath('highres-forest-static.png')})
  await page.setViewportSize({width:1280,height:800})
  await page.locator('[data-camera="world"]').click()
  await expect(page.locator('#world-image')).toHaveAttribute('src',/wide-v2/)
  await expect.poll(dimensions).toEqual([3344,1882])
  await page.screenshot({path:info.outputPath('highres-wide.png')})
})

retinaTest('retina regional surface draws at device density rather than full-map downsampling',async({page},info)=>{
  await page.setViewportSize({width:390,height:844}); await boot(page)
  await page.locator('[data-region="forest"]').click()
  await expect(page.locator('.world-plane')).toHaveAttribute('data-life','running')
  await expect.poll(()=>page.locator('.map-life-surface').evaluate(e=>[(e as HTMLCanvasElement).width,(e as HTMLCanvasElement).height])).toEqual([1170,2532])
  await page.locator('[data-camera="in"]').click()
  await page.waitForTimeout(400)
  await page.screenshot({path:info.outputPath('retina-forest.png')})
  await page.setViewportSize({width:1280,height:800})
  await expect.poll(()=>page.locator('.map-life-surface').evaluate(e=>(e as HTMLCanvasElement).width*(e as HTMLCanvasElement).height)).toBeLessThanOrEqual(3_205_000)
})
